// "use client"

import { BrowserRouter } from 'react-router-dom';
import { Geist, Geist_Mono } from "next/font/google";
import Nextnav from 



import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nextnav/>
        {children}

       {/* menggunakan react router dom*/}
        
         {/* <BrowserRouter>
        <nav/>
        </BrowserRouter> */}
      </body>
    </html>
  );
}
